### ISSUE TITLE
World.Spawn makes error.

### ISSUE THREAD

**Issue by dretax** [Notulp/Fougerite#57]
go = World.Spawn(file.GetSetting('Part' + str(i), 'Prefab'), spawnPos.x, spawnPos.y, spawnPos.z, spawnRot)

;struct_wood_foundation

[4/6/2015 3:55:53 PM] [Error] Traceback (most recent call last):
  File "<string>", line 116, in On_Command
SystemError: Object reference not set to an instance of an object

Try catch
[4/6/2015 3:59:55 PM] [Error] Traceback (most recent call last):
  File "<string>", line 121, in On_Command
UnboundLocalError: Local variable 'go' referenced before assignment.

Seems like it doesn't even return an entity..

**Comment by dretax** [comment]
https://github.com/Notulp/Fougerite/blob/master/Fougerite/Fougerite/Zone3D.cs#L110

Confirms that
